---
version: '2'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis-gotu
    command: redis-server --requirepass "redis" --loglevel debug

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgres-gotu
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gotu
