// Code generated by mockery v2.42.0. DO NOT EDIT.

package transactions

import mock "github.com/stretchr/testify/mock"

// GetTransactionsRepoInterface is an autogenerated mock type for the GetTransactionsRepoInterface type
type GetTransactionsRepoInterface struct {
	mock.Mock
}

type GetTransactionsRepoInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *GetTransactionsRepoInterface) EXPECT() *GetTransactionsRepoInterface_Expecter {
	return &GetTransactionsRepoInterface_Expecter{mock: &_m.Mock}
}

// NewGetTransactionsRepoInterface creates a new instance of GetTransactionsRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetTransactionsRepoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetTransactionsRepoInterface {
	mock := &GetTransactionsRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
