// Code generated by mockery v2.42.0. DO NOT EDIT.

package shopping_cart

import (
	models "gotu-bookstore/cmd/gotu-bookstore/models"

	mock "github.com/stretchr/testify/mock"
)

// BookRepoInterface is an autogenerated mock type for the BookRepoInterface type
type BookRepoInterface struct {
	mock.Mock
}

type BookRepoInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *BookRepoInterface) EXPECT() *BookRepoInterface_Expecter {
	return &BookRepoInterface_Expecter{mock: &_m.Mock}
}

// GetById provides a mock function with given fields: id
func (_m *BookRepoInterface) GetById(id string) (*models.Books, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *models.Books
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Books, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Books); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Books)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookRepoInterface_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type BookRepoInterface_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - id string
func (_e *BookRepoInterface_Expecter) GetById(id interface{}) *BookRepoInterface_GetById_Call {
	return &BookRepoInterface_GetById_Call{Call: _e.mock.On("GetById", id)}
}

func (_c *BookRepoInterface_GetById_Call) Run(run func(id string)) *BookRepoInterface_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *BookRepoInterface_GetById_Call) Return(_a0 *models.Books, _a1 error) *BookRepoInterface_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookRepoInterface_GetById_Call) RunAndReturn(run func(string) (*models.Books, error)) *BookRepoInterface_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// NewBookRepoInterface creates a new instance of BookRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookRepoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookRepoInterface {
	mock := &BookRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
