// Code generated by mockery v2.42.0. DO NOT EDIT.

package shopping_cart

import (
	contractsshopping_cart "gotu-bookstore/cmd/gotu-bookstore/contracts/shopping_cart"

	mock "github.com/stretchr/testify/mock"
)

// PostShoppingCartCheckoutServiceInterface is an autogenerated mock type for the PostShoppingCartCheckoutServiceInterface type
type PostShoppingCartCheckoutServiceInterface struct {
	mock.Mock
}

type PostShoppingCartCheckoutServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *PostShoppingCartCheckoutServiceInterface) EXPECT() *PostShoppingCartCheckoutServiceInterface_Expecter {
	return &PostShoppingCartCheckoutServiceInterface_Expecter{mock: &_m.Mock}
}

// ProcessingPostShoppingCartCheckout provides a mock function with given fields:
func (_m *PostShoppingCartCheckoutServiceInterface) ProcessingPostShoppingCartCheckout() (*contractsshopping_cart.PostShoppingCartCheckoutResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProcessingPostShoppingCartCheckout")
	}

	var r0 *contractsshopping_cart.PostShoppingCartCheckoutResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*contractsshopping_cart.PostShoppingCartCheckoutResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *contractsshopping_cart.PostShoppingCartCheckoutResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contractsshopping_cart.PostShoppingCartCheckoutResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostShoppingCartCheckoutServiceInterface_ProcessingPostShoppingCartCheckout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessingPostShoppingCartCheckout'
type PostShoppingCartCheckoutServiceInterface_ProcessingPostShoppingCartCheckout_Call struct {
	*mock.Call
}

// ProcessingPostShoppingCartCheckout is a helper method to define mock.On call
func (_e *PostShoppingCartCheckoutServiceInterface_Expecter) ProcessingPostShoppingCartCheckout() *PostShoppingCartCheckoutServiceInterface_ProcessingPostShoppingCartCheckout_Call {
	return &PostShoppingCartCheckoutServiceInterface_ProcessingPostShoppingCartCheckout_Call{Call: _e.mock.On("ProcessingPostShoppingCartCheckout")}
}

func (_c *PostShoppingCartCheckoutServiceInterface_ProcessingPostShoppingCartCheckout_Call) Run(run func()) *PostShoppingCartCheckoutServiceInterface_ProcessingPostShoppingCartCheckout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PostShoppingCartCheckoutServiceInterface_ProcessingPostShoppingCartCheckout_Call) Return(_a0 *contractsshopping_cart.PostShoppingCartCheckoutResponse, _a1 error) *PostShoppingCartCheckoutServiceInterface_ProcessingPostShoppingCartCheckout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PostShoppingCartCheckoutServiceInterface_ProcessingPostShoppingCartCheckout_Call) RunAndReturn(run func() (*contractsshopping_cart.PostShoppingCartCheckoutResponse, error)) *PostShoppingCartCheckoutServiceInterface_ProcessingPostShoppingCartCheckout_Call {
	_c.Call.Return(run)
	return _c
}

// NewPostShoppingCartCheckoutServiceInterface creates a new instance of PostShoppingCartCheckoutServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostShoppingCartCheckoutServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostShoppingCartCheckoutServiceInterface {
	mock := &PostShoppingCartCheckoutServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
