// Code generated by mockery v2.42.0. DO NOT EDIT.

package shopping_cart

import (
	contractsshopping_cart "gotu-bookstore/cmd/gotu-bookstore/contracts/shopping_cart"

	mock "github.com/stretchr/testify/mock"
)

// PutShoppingCartServiceInterface is an autogenerated mock type for the PutShoppingCartServiceInterface type
type PutShoppingCartServiceInterface struct {
	mock.Mock
}

type PutShoppingCartServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *PutShoppingCartServiceInterface) EXPECT() *PutShoppingCartServiceInterface_Expecter {
	return &PutShoppingCartServiceInterface_Expecter{mock: &_m.Mock}
}

// ProcessingPutShoppingCart provides a mock function with given fields: request
func (_m *PutShoppingCartServiceInterface) ProcessingPutShoppingCart(request contractsshopping_cart.PutShoppingCartRequest) (*contractsshopping_cart.ShoppingCartResponse, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for ProcessingPutShoppingCart")
	}

	var r0 *contractsshopping_cart.ShoppingCartResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(contractsshopping_cart.PutShoppingCartRequest) (*contractsshopping_cart.ShoppingCartResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(contractsshopping_cart.PutShoppingCartRequest) *contractsshopping_cart.ShoppingCartResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contractsshopping_cart.ShoppingCartResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(contractsshopping_cart.PutShoppingCartRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutShoppingCartServiceInterface_ProcessingPutShoppingCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessingPutShoppingCart'
type PutShoppingCartServiceInterface_ProcessingPutShoppingCart_Call struct {
	*mock.Call
}

// ProcessingPutShoppingCart is a helper method to define mock.On call
//   - request contractsshopping_cart.PutShoppingCartRequest
func (_e *PutShoppingCartServiceInterface_Expecter) ProcessingPutShoppingCart(request interface{}) *PutShoppingCartServiceInterface_ProcessingPutShoppingCart_Call {
	return &PutShoppingCartServiceInterface_ProcessingPutShoppingCart_Call{Call: _e.mock.On("ProcessingPutShoppingCart", request)}
}

func (_c *PutShoppingCartServiceInterface_ProcessingPutShoppingCart_Call) Run(run func(request contractsshopping_cart.PutShoppingCartRequest)) *PutShoppingCartServiceInterface_ProcessingPutShoppingCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(contractsshopping_cart.PutShoppingCartRequest))
	})
	return _c
}

func (_c *PutShoppingCartServiceInterface_ProcessingPutShoppingCart_Call) Return(_a0 *contractsshopping_cart.ShoppingCartResponse, _a1 error) *PutShoppingCartServiceInterface_ProcessingPutShoppingCart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PutShoppingCartServiceInterface_ProcessingPutShoppingCart_Call) RunAndReturn(run func(contractsshopping_cart.PutShoppingCartRequest) (*contractsshopping_cart.ShoppingCartResponse, error)) *PutShoppingCartServiceInterface_ProcessingPutShoppingCart_Call {
	_c.Call.Return(run)
	return _c
}

// NewPutShoppingCartServiceInterface creates a new instance of PutShoppingCartServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPutShoppingCartServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PutShoppingCartServiceInterface {
	mock := &PutShoppingCartServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
